ALTER TABLE "User"
ADD COLUMN IF NOT EXISTS "operationalStatus" TEXT NOT NULL DEFAULT 'READY',
ADD COLUMN IF NOT EXISTS "operationalStatusUpdatedAt" TIMESTAMP(3);

ALTER TABLE "Chair"
ADD COLUMN IF NOT EXISTS "operationalStatus" TEXT NOT NULL DEFAULT 'READY',
ADD COLUMN IF NOT EXISTS "operationalStatusUpdatedAt" TIMESTAMP(3);

